before_commands:
    - "composer install"

filter:
    excluded_paths: [vendor/*]

tools:
    php_code_coverage: true
    php_cpd: true
    php_pdepend:
        excluded_dirs: [vendor]
    php_code_sniffer:
        extensions:
            - php
        filter:
            excluded_paths: [vendor/*]
        config:
            encoding: utf8
            standard: "PSR2"
